=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/Expresions/14-patterns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="patrons">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="patroA" type="patroA" maxOccurs="2"/>
                <xs:element name="patroB" type="patroB"/>
                <xs:element name="patroC" type="patroC"/>
                <xs:element name="patroD" type="patroD" maxOccurs="2"/>
                <xs:element name="patroE" type="patroE"/>
                <xs:element name="patroF" type="patroF"/>
                <xs:element name="patroG" type="patroG"/>
                <xs:element name="patroH" type="patroH"/>
                <xs:element name="patroI" type="patroI" maxOccurs="2"/>
                <xs:element name="patroJ" type="patroJ"/>
                <xs:element name="patroK" type="patroK" maxOccurs="2"/>
                <xs:element name="patroL" type="patroL" maxOccurs="2"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="patroA">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5,8}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroB">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroC">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}[a-z]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroD">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-D]|[a-d]){3}[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroE">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-5]{3}[a-d]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroF">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroG">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z][0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroH">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}-[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroI">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9].[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroJ">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}-[0-9]{4}\.V[0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroK">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-b][1-2]-[a-z]{3,5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="patroL">
        <xs:restriction base="xs:string">
            <xs:pattern value="a+b+c*"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/Expresions/pattern.xml
<?xml version="1.0" encoding="UTF-8" ?>

<patrons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="14-patterns.xsd">

    <!-- de 5 a 8 números -->

    <patroA>12345678</patroA>

    <patroA>99999999</patroA>

    <!-- 5 lletras majúscules -->

    <patroB>LMSGI</patroB>

    <!-- 3 lletres majúscules seguit de 3 minúscules -->

    <patroC>ABCdef</patroC>

    <!-- que tenga 3 letras mayúsculas o minúsculas de la a a la d, seguido de 2 números -->

    <patroD>AdC99</patroD>

    <patroD>bBb11</patroD>

    <!-- que tenga 3 números de 0 a 5 seguido de una letra minúscula desde a - d -->

    <patroE>123a</patroE>

    <!-- tenga 3 bloque de 3 números separados por - -->

    <patroF>123-456-789</patroF>

    <!-- empiece por una letra y tenga 2 números -->

    <patroG>c18</patroG>

    <!-- Quiero la palabra LGA, seguido de un guión, seguido de 4 dígitos  -->

    <patroH>LGA-1115</patroH>

    <!-- Quiero 1 número - cualquier caracter - 1 letra mayúscula  -->

    <patroI>3#P</patroI>

    <patroI>9$Q</patroI>

    <!-- Quiero la palabra LGA, seguido de un guión, seguido de 4 dígitos .V y número  -->

    <patroJ>LGA-1115.V3</patroJ>

    <!-- a o b, 1 ó 2, un guión, de 3 a 5 letras -->

    <patroK>a2-aaa</patroK>

    <patroK>b1-ababa</patroK>

    <!-- al menos una a, al menos una b, 0 o muchas c -->

    <patroL>aaabbbbb</patroL>

    <patroL>abcccccc</patroL>

</patrons>
