=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/Paisos.dtd
<!ELEMENT paisos (pais+)>
<!ELEMENT pais (nom,continent,num_hab,govern)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT continent (#PCDATA)>
<!ELEMENT num_hab (#PCDATA)>
<!ELEMENT govern EMPTY>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/paisos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paisos SYSTEM "Paisos.dtd">
<paisos>
    <pais>
        <nom>Andorra</nom>
        <continent>Europa</continent>
        <num_hab>7500</num_hab>
        <govern/>
    </pais>
    <pais>
        <nom>Brasil</nom>
        <continent>Am√®rica</continent>
        <num_hab>60 milions</num_hab>
        <govern/>
    </pais>
</paisos>
