=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/videoclub.dtd
<!ELEMENT videoclub (peli+)>
<!ELEMENT peli (titulo, director, estreno, actores, generos, presupuesto, serie?)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST director pais CDATA #REQUIRED>
<!ELEMENT director (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT estreno (#PCDATA)>
<!ELEMENT actores (datos+)>
<!ATTLIST datos pais CDATA #REQUIRED>
<!ELEMENT datos (nombre, apellido)>
<!ELEMENT generos (genero+)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT presupuesto (#PCDATA)>
<!ELEMENT serie EMPTY>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "videoclub.dtd">
<videoclub>
    <peli>
        <titulo>
            Harry Potter and the Philosopher's Stone
        </titulo>
        <director pais="Estadounidense">
            <nombre>
                Chris
            </nombre>
            <apellido>
                Colombus
            </apellido>
        </director>
        <estreno>
            2001
        </estreno>
        <actores>
            <datos pais="Britanico">
                <nombre>
                    Daniel
                </nombre>
                <apellido>
                    Radcliffe
                </apellido>
            </datos>
            <datos pais="Britanico">
                <nombre>
                    Rupert
                </nombre>
                <apellido>
                    Grint
                </apellido>
            </datos>
            <datos pais="Britanico">
                <nombre>
                    Emma
                </nombre>
                <apellido>
                    Wattson
                </apellido>
            </datos>
        </actores>
        <generos>
            <genero>
                Fantasía
            </genero>
            <genero>
                Aventura
            </genero>
        </generos>
        <presupuesto>
            125-130 millones
        </presupuesto>
        <serie/>
    </peli>

    <peli>
        <titulo>
            Crouching Tiger, Hidden Dragon
        </titulo>
        <director pais="Taiwanés">
            <nombre>
                Ang
            </nombre>
            <apellido>
                Lee
            </apellido>
        </director>
        <estreno>
            2000
        </estreno>
        <actores>
            <datos pais="Hongkonés">
                <nombre>
                    Chow
                </nombre>
                <apellido>
                    Yun-fat
                </apellido>
            </datos>
            <datos pais="Malaya">
                <nombre>
                    Michelle
                </nombre>
                <apellido>
                    Yeoh
                </apellido>
            </datos>
            <datos pais="China">
                <nombre>
                    Zhang
                </nombre>
                <apellido>
                    Ziyi
                </apellido>
            </datos>
        </actores>
        <generos>
            <genero>
                Drama de artes marciales
            </genero>
        </generos>
        <presupuesto>
            17 millones
        </presupuesto>
    </peli>
    
    <peli>
        <titulo>
            Inglourious Basterds
        </titulo>
        <director pais="Estadounidense">
            <nombre>
                Quentin
            </nombre>
            <apellido>
                Tarantino
            </apellido>
        </director>
        <estreno>
            2009
        </estreno>
        <actores>
            <datos pais="Estadounidense">
                <nombre>
                    Brad
                </nombre>
                <apellido>
                    Pitt
                </apellido>
            </datos>
            <datos pais="Autríaco">
                <nombre>
                    Christoph
                </nombre>
                <apellido>
                    Waltz
                </apellido>
            </datos>
            <datos pais="Francesa">
                <nombre>
                    Mélanie
                </nombre>
                <apellido>
                    Laurent
                </apellido>
            </datos>
        </actores>
        <generos>
            <genero>
                Drama bélico
            </genero>
            <genero>
                Comedia negra
            </genero>
        </generos>
        <presupuesto>
            70-75 millones
        </presupuesto>
    </peli>

    <peli>
        <titulo>
            The Dark Knight
        </titulo>
        <director pais="Británico">
            <nombre>
                Christopher
            </nombre>
            <apellido>
                Nolan
            </apellido>
        </director>
        <estreno>
            2008
        </estreno>
        <actores>
            <datos pais="Británico">
                <nombre>
                    Christian
                </nombre>
                <apellido>
                    Bale
                </apellido>
            </datos>
            <datos pais="Australiano">
                <nombre>
                    Healt
                </nombre>
                <apellido>
                    Ledger
                </apellido>
            </datos>
            <datos pais="Estadounidense">
                <nombre>
                    Aaron
                </nombre>
                <apellido>
                    Eckhart
                </apellido>
            </datos>
        </actores>
        <generos>
            <genero>
                Acción
            </genero>
            <genero>
                Drama
            </genero>
            <genero>
                Thriller
            </genero>
        </generos>
        <presupuesto>
            185 millones
        </presupuesto>
    </peli>
</videoclub>
