=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/PruebaDeExamen/prueba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="departamentInformatica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="salaDeJuntes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pc" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[p|P][c|C]\d+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="ip">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="192\.168\.\d?\d?\d\.\d?\d?\d"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="mac">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([A-Z|0-9]{2}:){5}[A-Z|0-9]{2}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nomXarxa">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([a-z]|[A-Z]){2}([p]|[P])([a|A]|[e|E]|[i|I]|[o|O]|[u|U])"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="connexio" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[r|R][s|S][0-9][2,4,6,8]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="switch">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="xarxa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="idXarxa">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="([aei{1}ou]|[AEI{1}OU])?([a-z]|[A-Z])([aei{1}ou]|[AEI{1}OU])"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Rosetes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="R" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cableEthernet" maxOccurs="unbounded">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="\d\d(PC|SW|RS)\d\d-\d\d(PC|SW|RS)\d\d"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/PruebaDeExamen/Prueba.xml
<?xml version="1.0" encoding="UTF-8" ?>
<departamentInformatica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="prueba.xsd">
<!-- <!DOCTYPE departamentInformatica [
    <!ELEMENT departamentInformatica (salaDeJuntes)>
    <!ELEMENT salaDeJuntes (pc+,switch,Rosetes)>
    <!ATTLIST salaDeJuntes id CDATA #REQUIRED>
    <!ELEMENT pc (nom,ip,mac,nomXarxa,connexio?)>
    <!ELEMENT nom (#PCDATA)>
    <!ELEMENT ip (#PCDATA)>
    <!ELEMENT mac (#PCDATA)>
    <!ELEMENT nomXarxa (#PCDATA)>
    <!ELEMENT connexio (#PCDATA)>
    <!ELEMENT switch (xarxa)>
    <!ATTLIST switch id CDATA #REQUIRED>
    <!ELEMENT xarxa (idXarxa)>
    <!ELEMENT idXarxa (#PCDATA)>
    <!ELEMENT Rosetes (R+)>
    <!ELEMENT R (cableEthernet+)>
    <!ATTLIST R id CDATA #REQUIRED>
    <!ELEMENT cableEthernet (#PCDATA)>
]> -->
    <salaDeJuntes id="04">
        <pc>
            <nom>pc01</nom>
            <ip>192.168.2.41</ip>
            <mac>12:34:A0:87:78:BF</mac>
            <nomXarxa>gopokupu</nomXarxa>
        </pc>
        <pc>
            <nom>pc02</nom>
            <ip>192.168.2.42</ip>
            <mac>12:34:A0:C0:12:FA</mac>
            <nomXarxa>vegepetapa</nomXarxa>
            <connexio>RS02</connexio>
        </pc>
        <switch id="SW01">
            <xarxa>
                <idXarxa>Aladino</idXarxa>
            </xarxa>
        </switch>
        <Rosetes>
            <R id="RS02">
                <cableEthernet>04RS02-04SW01</cableEthernet>
            </R>
            <R id="RS04-06">
                <cableEthernet>04RS04-04SW01</cableEthernet>
                <cableEthernet>04RS06-04SW01</cableEthernet>
            </R>
        </Rosetes>
    </salaDeJuntes>
</departamentInformatica>
