<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Restaurant [
    <!ELEMENT Restaurant (infoGeneral, menu)>
    <!ELEMENT infoGeneral (nom, alias, xefs, ciutat, telefon, diaVisita)>
    <!ELEMENT nom EMPTY>
    <!ATTLIST nom name CDATA #REQUIRED>
    <!ELEMENT alias (#PCDATA)>
    <!ELEMENT xefs (xef)>
    <!ELEMENT xef (#PCDATA)>
    <!ELEMENT ciutat (#PCDATA)>
    <!ELEMENT telefon (#PCDATA)>
    <!ELEMENT diaVisita (dia,mes,any)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT any (#PCDATA)>
    <!ELEMENT menu (plats)>
    <!ELEMENT plats (plat+)>
    <!ELEMENT plat (nomPlat, preu, categoria, apteCeliac, valoracio)>
    <!ELEMENT nomPlat (#PCDATA)>
    <!ELEMENT preu (#PCDATA)>
    <!ELEMENT categoria EMPTY>
    <!ATTLIST categoria cat CDATA #REQUIRED>
    <!ELEMENT apteCeliac ANY>
    <!ELEMENT valoracio (#PCDATA)>
]>

<Restaurant>
    <infoGeneral>
        <nom name="La mar al cor"/>
        <alias>TAR9MR</alias>
        <xefs>
            <xef>Carme Mola</xef>
        </xefs>
        <ciutat>Tarragona</ciutat>
        <telefon>977-216-543</telefon>
        <diaVisita>
            <dia>1</dia>
            <mes>7</mes>
            <any>2023</any>
        </diaVisita>
    </infoGeneral>
    <menu>
        <plats>
            <plat>
                <nomPlat>Amanida Cesar</nomPlat>
                <preu>8.50€</preu>
                <categoria cat="Principal"/>
                <apteCeliac></apteCeliac>
                <valoracio>4</valoracio>
            </plat>
            <plat>
                <nomPlat>Rap a l'all cremat</nomPlat>
                <preu>18.99€</preu>
                <categoria cat="Principal"/>
                <apteCeliac></apteCeliac>
                <valoracio>5</valoracio>
            </plat>
            <plat>
                <nomPlat>Pizza margarita de coliflor</nomPlat>
                <preu>9.99€</preu>
                <categoria cat="Principal"/>
                <apteCeliac>Si</apteCeliac>
                <valoracio>2</valoracio>
            </plat>
            <plat>
                <nomPlat>Coulant de xocolata</nomPlat>
                <preu>5.90€</preu>
                <categoria cat="Postre"/>
                <apteCeliac></apteCeliac>
                <valoracio>5</valoracio>
            </plat>
        </plats>
    </menu>
</Restaurant>