=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/Examen/Examen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Restaurante">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Restaurant">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="infoGeneral">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom">
                                            <xs:complexType>
                                                <xs:sequence></xs:sequence>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="alias">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z]{3}[0-9][0-9]?(MR|NMR)"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="xefs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="xef" maxOccurs="unbounded">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="([A-Z][a-z]+ [A-Z][a-z]+( )?)+"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="ciutat">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z](([A-Z]|[a-z])+( )?)+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="telefon">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="6|9\d{2}-\d{3}-\d{3}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="diaVisita">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[1|2][1-9]?|3[01]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="mes">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="1[0-2]|[1-9]"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="any">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="20[0-9]{2}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="menu">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="plats">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="plat" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nomPlat" type="xs:string"/>
                                                                <xs:element name="preu">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:pattern value="[1-9][1-9]*\.[0-9]{2}â‚¬"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="categoria">
                                                                    <xs:complexType>
                                                                        <xs:sequence></xs:sequence>
                                                                        <xs:attribute name="cat" type="xs:string" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="apteCeliac" type="xs:string"/>
                                                                <xs:element name="valoracio">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:pattern value="[0-5]"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/Examen/SuperguiaDelicatessen.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Restaurante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Examen.xsd">
<Restaurant>
    <infoGeneral>
        <nom name="La mar al cor"/>
        <alias>TAR9MR</alias>
        <xefs>
            <xef>Carme Mola</xef>
        </xefs>
        <ciutat>Tarragona</ciutat>
        <telefon>977-216-543</telefon>
        <diaVisita>
            <dia>1</dia>
            <mes>7</mes>
            <any>2023</any>
        </diaVisita>
    </infoGeneral>
    <menu>
        <plats>
            <plat>
                <nomPlat>Amanida Cesar</nomPlat>
                <preu>8.50€</preu>
                <categoria cat="Principal"/>
                <apteCeliac></apteCeliac>
                <valoracio>4</valoracio>
            </plat>
            <plat>
                <nomPlat>Rap a l'all cremat</nomPlat>
                <preu>18.99€</preu>
                <categoria cat="Principal"/>
                <apteCeliac></apteCeliac>
                <valoracio>5</valoracio>
            </plat>
            <plat>
                <nomPlat>Pizza margarita de coliflor</nomPlat>
                <preu>9.99€</preu>
                <categoria cat="Principal"/>
                <apteCeliac>Si</apteCeliac>
                <valoracio>2</valoracio>
            </plat>
            <plat>
                <nomPlat>Coulant de xocolata</nomPlat>
                <preu>5.90€</preu>
                <categoria cat="Postre"/>
                <apteCeliac></apteCeliac>
                <valoracio>5</valoracio>
            </plat>
        </plats>
    </menu>
</Restaurant>
</Restaurante>
