=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/xsd/begudes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="begudes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="beguda" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="imatge" type="xs:string"/>
                            <xs:element name="descripcio" type="xs:string"/>
                            <xs:element name="graduacio" type="xs:string" minOccurs="0"/>
                            <xs:element name="cost" type="xs:string" maxOccurs="2"/>
                            <xs:element name="origen" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/xsd/begudes.xml
<?xml version="1.0" encoding="UTF-8"?>
<begudes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="begudes.xsd">
<beguda>
<nom>Llimonada</nom>
<imatge>http://www.xyz.com/llimonada</imatge>
<descripcio>Llimonada 100% natural</descripcio>
<cost>0,45 euros</cost>
<origen>Catalunya</origen>
</beguda>
<beguda>
<nom>Cervesa Artesana ASIX</nom>
<imatge> http://www.xyz.com/cervesaasix</imatge>
<descripcio>Cervesa Artesana ASIX</descripcio>
<graduacio>14,5ยบ</graduacio>
<cost>0,50 euros</cost>
<cost>0,30 dolars</cost>
<origen>Catalunya</origen>
</beguda>
</begudes>
