=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/xsd/edificis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="edificis">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ciutat" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" />
                            <xs:element name="carrer" type="xs:string"/>
                            <xs:element name="Oficines" type="descOficina"/>
                            <xs:element name="habitatge" type="descHabitatge" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="descOficina">
        <xs:sequence>
            <xs:element name="num" type="xs:integer" />
            <xs:element name="Planta" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="num" type="xs:integer" />
                        <xs:element name="oficina" type="xs:string" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="descHabitatge">
        <xs:sequence>
            <xs:element name="num" type="xs:integer" />
            <xs:element name="botiga" minOccurs="0" />
            <xs:element name="Planta" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pis" type="xs:string" maxOccurs="unbounded"/>
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="terrasa" type="xs:string" minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                    </xs:sequence>
                    <xs:attribute name="num" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/edificis.xml
<?xml version="1.0" encoding="UTF-8"?>
<edificis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsd/edificis.xsd">
    <ciutat>
        <nom>
            Barcelona
        </nom>
        <carrer>
            Balmes
        </carrer>
        <Oficines>
            <num>
                5
            </num>
            <Planta>
                <num>
                    1
                </num>
                <oficina>
                    tamany = 150m
                </oficina>
            </Planta>
            <Planta>
                <num>
                    2
                </num>
                <oficina>
                    tamany = 70m
                </oficina>
                <oficina>
                    tamany = 70m
                </oficina>
            </Planta>
        </Oficines>
        <habitatge>
            <num>
                7
            </num>
            <botiga>
                tamany = 150m
            </botiga>
            <Planta>
                <num>
                    1
                </num>
                <pis num="1">
                    tamany = 60m
                </pis>
                <pis num="2">
                    tamany = 60m
                </pis>
                <pis num="3">
                    tamany = 60m
                </pis>
            </Planta>
            <Planta>
                <num>
                    2
                </num>
                <pis num="1">
                    tamany = 60m
                </pis>
                <pis num="2">
                    tamany = 60m
                </pis>
                <pis num="3">
                    tamany = 60m
                </pis> 
            </Planta>
            <Planta>
                <num>
                    3
                </num>
                <pis num="1">
                    tamany = 60m
                </pis>
                <pis num="2">
                    tamany = 60m
                </pis>
                <pis num="3">
                    tamany = 60m
                </pis>
            </Planta>
            <Planta num="4">
                <num>
                    4
                </num>
                <pis num="1">
                    tamany = 60m
                </pis>
                <pis num="2">
                    tamany = 60m
                </pis>
                <pis num="3">
                    tamany = 60m
                </pis>
            </Planta>
            <Planta num="5">
                <pis num="1" tamany="70">
                    <terrasa tamany="15">
                        
                    </terrasa>
                </pis>
            </Planta>
        </habitatge>
    </ciutat>
</edificis>
