=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/xsd/monitors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="monitors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="monitor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mida" type="xs:string" />
                            <xs:element name="rati" type="xs:string"/>
                            <xs:element name="dataLlancament" type="xs:string"/>
                            <xs:element name="caracteristica" type="xs:string" minOccurs="0" maxOccurs="2"/>
                            <xs:element name="preu" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="tipus" type="xs:string" use="required" />
                        <xs:attribute name="model" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SergioReyGarciaInstitutJaumeHuguet/Programacio/UF1/xsd/monitors.xml
<?xml version="1.0" encoding="UTF-8"?>
<monitors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="monitors.xsd">
    <monitor tipus="LED" model="m0010">
        <mida>24</mida>
        <rati>16:9</rati>
        <dataLlancament>2009-09-10</dataLlancament>
        <caracteristica>100% sRGB color </caracteristica>
        <caracteristica>High contrast ratio</caracteristica>
        <preu>200</preu>
    </monitor>
    <monitor tipus="LCD" model="m0101">
        <mida>20</mida>
        <rati>16:10</rati>
        <dataLlancament>2008-09-10</dataLlancament>
        <caracteristica>Alt ajustament</caracteristica>
        <preu>120</preu>
    </monitor>
    <monitor tipus="CRT" model="c0120">
        <mida>15</mida>
        <rati>4:3</rati>
        <dataLlancament>2002-09-10</dataLlancament>
        <preu>50</preu>
    </monitor>
</monitors>
